version: "3.9"
services:
  smarttraderbot:
    build: .
    container_name: smarttraderbot_v8_4
    restart: unless-stopped
    env_file: .env
    ports:
      - "8080:8080"
    environment:
      - FLASK_ENV=production
      - GUNICORN_CMD_ARGS=--timeout 120


